#!/bin/sh
## $HOME/.local/bin

export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/dri/iris_dri.so"
export MESA_LOADER_DRIVER_OVERRIDE="iris"
export JAVA_TOOL_OPTIONS="-Djogl.disable.openglarbcontext=1"

ulimit -n 2048

$HOME/MATLAB/R2024b/bin/matlab
